spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5441/mireabankapp
    username: mireabankapp
    password: mireabankapp
server:
  servlet:
    session:
      timeout: 10m
      cookie:
        http-only: true

