spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
server:
  servlet:
    session:
      timeout: 10m
      cookie:
        secure: true
