spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5441/mireabankapp
    username: mireabankapp
    password: mireabankapp
  liquibase:
    change-log: classpath:/db/changelog/liquibase-changelog.xml
server:
  servlet:
    session:
      timeout: 1m
      cookie:
        http-only: true

