spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5441/mireabankapp
    username: mireabankapp
    password: mireabankapp
  liquibase:
    change-log: classpath:/db/changelog/liquibase-changelog.xml
server:
  servlet:
    session:
      timeout: 10m
      cookie:
        http-only: true

